#!/bin/sh
# Shared helpers for the Phase 3 lab container config.

write_lab_config() {
    config_file=$1
    name=$2
    rootfs_dir=$3

    cat >"$config_file" <<EOF
# Generated by lxc-on-dsm Phase 3 lab setup.
#
# Keep this config intentionally minimal for DSM compatibility.
# The upstream LXC common.conf may reference capabilities such as mac_admin and
# mac_override that are not known by the DSM/Entware capability headers used in
# the lab build, causing config parsing to fail before any container starts.
lxc.arch = linux64
lxc.uts.name = ${name}
lxc.rootfs.path = dir:${rootfs_dir}
lxc.tty.max = 0
lxc.pty.max = 16
lxc.console.path = none
lxc.net.0.type = none
lxc.start.auto = 0
lxc.mount.auto = proc:mixed sys:ro cgroup:mixed
lxc.init.cmd = /bin/sh
EOF
}
