#!/bin/sh
# Create a stopped LXC lab container from a packaged Alpine minirootfs image.
# Dry-run by default. Does not start containers or change networking.
set -eu

usage() {
    printf '%s\n' "Usage: $0 --name NAME [--prefix DIRECTORY] [--state-dir DIRECTORY] [--image FILE] [--network-type none|empty|macvlan] [--parent-if IFACE] [--create]"
}

PACKAGE=lxc-on-dsm
BASE="/var/packages/${PACKAGE}"
TARGET="${BASE}/target"

prefix=/volume1/@lxc/lab/opt
state_dir=/volume1/@lxc/lab/containers
image_file="${TARGET}/images/alpine-minirootfs.tar.gz"
name=
network_type=none
parent_if=eth0
create=0

while [ "$#" -gt 0 ]; do
    case "$1" in
        --name) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; name=$2; shift 2 ;;
        --prefix) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; prefix=$2; shift 2 ;;
        --state-dir) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; state_dir=$2; shift 2 ;;
        --image) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; image_file=$2; shift 2 ;;
        --network-type) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; network_type=$2; shift 2 ;;
        --parent-if) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; parent_if=$2; shift 2 ;;
        --create) create=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

[ -n "$name" ] || { usage >&2; exit 2; }

case "$prefix" in /volume[0-9]*/@lxc/lab/opt) ;; *) printf 'Unexpected LXC prefix: %s\n' "$prefix" >&2; exit 2 ;; esac
case "$state_dir" in /volume[0-9]*/@lxc/lab/containers) ;; *) printf 'Unexpected state dir: %s\n' "$state_dir" >&2; exit 2 ;; esac
case "$image_file" in
    "${TARGET}/images/"*.tar.gz|/volume[0-9]*/@lxc/lab/images/*.tar.gz) ;;
    *) printf 'Unexpected image path: %s\n' "$image_file" >&2; exit 2 ;;
esac
case "$name" in *[!A-Za-z0-9_.-]*|'') printf 'Invalid container name: %s\n' "$name" >&2; exit 2 ;; esac
case "$network_type" in none|empty|macvlan) ;; *) printf 'Unsupported network type: %s\n' "$network_type" >&2; exit 2 ;; esac
case "$parent_if" in *[!A-Za-z0-9_.:-]*|'') printf 'Invalid parent interface: %s\n' "$parent_if" >&2; exit 2 ;; esac
if [ ${#parent_if} -gt 15 ]; then
    printf 'Parent interface name is too long for Linux interfaces: %s\n' "$parent_if" >&2
    exit 2
fi

[ -r "$image_file" ] || { printf 'Missing packaged image: %s\n' "$image_file" >&2; exit 1; }
if [ "$create" -eq 1 ] && [ "$(id -u)" -ne 0 ]; then
    printf '%s\n' 'Container creation requires uid=0.' >&2
    exit 1
fi

container_dir="${state_dir}/${name}"
rootfs_dir="${container_dir}/rootfs"
config_file="${container_dir}/config"

printf '%s\n' '# Packaged LXC container create plan'
printf '\n'
printf 'package=%s\n' "$PACKAGE"
printf 'create=%s\n' "$create"
printf 'container=%s\n' "$name"
printf 'prefix=%s\n' "$prefix"
printf 'state_dir=%s\n' "$state_dir"
printf 'container_dir=%s\n' "$container_dir"
printf 'rootfs=%s\n' "$rootfs_dir"
printf 'config=%s\n' "$config_file"
printf 'image=%s\n' "$image_file"
printf 'network_type=%s\n' "$network_type"
[ "$network_type" != macvlan ] || printf 'parent_if=%s\n' "$parent_if"
printf '\n'

if [ "$create" -ne 1 ]; then
    [ ! -e "$container_dir" ] || printf 'WARN: container already exists: %s\n' "$container_dir"
    printf '%s\n' 'Result: PACKAGED CONTAINER CREATE DRY RUN COMPLETE. No files were written and no container was started.'
    exit 0
fi

[ ! -e "$container_dir" ] || { printf 'Container already exists: %s\n' "$container_dir" >&2; exit 1; }

mkdir -p "$rootfs_dir"
gzip -dc "$image_file" | tar -xf - -C "$rootfs_dir"

cat >"$config_file" <<EOF
# Generated by lxc-on-dsm packaged container create.
#
# Keep this config intentionally minimal for DSM compatibility.
lxc.arch = linux64
lxc.uts.name = ${name}
lxc.rootfs.path = dir:${rootfs_dir}
lxc.tty.max = 0
lxc.pty.max = 16
lxc.console.path = none
lxc.net.0.type = ${network_type}
lxc.start.auto = 0
lxc.mount.auto = proc:mixed sys:ro cgroup:mixed
lxc.init.cmd = /bin/sh
EOF

if [ "$network_type" = macvlan ]; then
    cat >>"$config_file" <<EOF
lxc.net.0.link = ${parent_if}
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.macvlan.mode = bridge
EOF
fi

chmod 0700 "$container_dir"
chmod 0600 "$config_file"

printf '%s\n' '# Packaged LXC container create summary'
printf '\n'
printf 'container=%s\n' "$name"
printf 'container_dir=%s\n' "$container_dir"
printf 'config=%s\n' "$config_file"
printf 'network_type=%s\n' "$network_type"
printf '\n'
printf '%s\n' 'Result: PACKAGED CONTAINER CREATED STOPPED. No container was started and no networking was changed.'
