#!/bin/sh
# Create a stopped, networkless Alpine lab container. Does not start it.
set -eu
PATH="/opt/bin:/opt/sbin:${PATH}"

usage() {
    printf '%s\n' "Usage: $0 --prefix DIRECTORY [--name NAME] [--state-dir DIRECTORY] [--manifest FILE] [--sources DIRECTORY]"
}

prefix=""
name=alpine-lab
state_dir=/volume1/@lxc/lab/containers
manifest=manifests/lxc-userspace.env
sources_dir="${PWD}/build/sources"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --prefix) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; prefix=$2; shift 2 ;;
        --name) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; name=$2; shift 2 ;;
        --state-dir) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; state_dir=$2; shift 2 ;;
        --manifest) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; manifest=$2; shift 2 ;;
        --sources) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; sources_dir=$2; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

[ -n "$prefix" ] || { usage >&2; exit 2; }
[ -r "$manifest" ] || { printf 'Missing manifest: %s\n' "$manifest" >&2; exit 2; }
. "$manifest"

case "$prefix" in /*) ;; *) printf 'Prefix must be absolute: %s\n' "$prefix" >&2; exit 2 ;; esac
case "$state_dir" in /*) ;; *) printf 'State dir must be absolute: %s\n' "$state_dir" >&2; exit 2 ;; esac
case "$name" in *[!A-Za-z0-9_.-]*|'') printf 'Invalid container name: %s\n' "$name" >&2; exit 2 ;; esac

rootfs_tar="${sources_dir}/alpine-minirootfs-${ALPINE_MINIROOTFS_VERSION}-x86_64.tar.gz"
[ -r "$rootfs_tar" ] || {
    printf 'Missing Alpine rootfs tarball: %s\nRun scripts/fetch-sources.sh first.\n' "$rootfs_tar" >&2
    exit 1
}

container_dir="${state_dir}/${name}"
rootfs_dir="${container_dir}/rootfs"
config_file="${container_dir}/config"
[ ! -e "$container_dir" ] || {
    printf 'Container already exists: %s\n' "$container_dir" >&2
    exit 1
}

mkdir -p "$rootfs_dir"
gzip -dc "$rootfs_tar" | tar -xf - -C "$rootfs_dir"

cat >"$config_file" <<EOF
# Generated by lxc-on-dsm Phase 3 lab setup.
lxc.include = ${prefix}/share/lxc/config/common.conf
lxc.arch = linux64
lxc.uts.name = ${name}
lxc.rootfs.path = dir:${rootfs_dir}
lxc.tty.max = 0
lxc.pty.max = 16
lxc.net.0.type = none
lxc.start.auto = 0
lxc.mount.auto = proc:mixed sys:ro cgroup:mixed
lxc.init.cmd = /bin/sh
EOF

printf 'Created stopped lab container: %s\n' "$container_dir"
printf 'Config: %s\n' "$config_file"
printf 'No container was started.\n'
