#!/bin/sh
# Write a reproducible local macvlan lab profile. Does not change networking.
set -eu

usage() {
    printf '%s\n' "Usage: $0 --prefix DIRECTORY [--name NAME] [--state-dir DIRECTORY] [--parent-if IFACE] [--shim-if IFACE] [--host-cidr CIDR] [--output FILE]"
}

prefix=
name=alpine-macvlanlab
state_dir=/volume1/@lxc/lab/containers
parent_if=eth0
shim_if=lxcshim0
host_cidr=
output_file=config/lab-macvlan.env

while [ "$#" -gt 0 ]; do
    case "$1" in
        --prefix) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; prefix=$2; shift 2 ;;
        --name) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; name=$2; shift 2 ;;
        --state-dir) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; state_dir=$2; shift 2 ;;
        --parent-if) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; parent_if=$2; shift 2 ;;
        --shim-if) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; shim_if=$2; shift 2 ;;
        --host-cidr) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; host_cidr=$2; shift 2 ;;
        --output) [ "$#" -ge 2 ] || { usage >&2; exit 2; }; output_file=$2; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'Unknown argument: %s\n' "$1" >&2; usage >&2; exit 2 ;;
    esac
done

[ -n "$prefix" ] || { usage >&2; exit 2; }
case "$prefix" in /*) ;; *) printf 'Prefix must be absolute: %s\n' "$prefix" >&2; exit 2 ;; esac
case "$state_dir" in /*) ;; *) printf 'State dir must be absolute: %s\n' "$state_dir" >&2; exit 2 ;; esac
case "$name" in *[!A-Za-z0-9_.-]*|'') printf 'Invalid container name: %s\n' "$name" >&2; exit 2 ;; esac
case "$parent_if" in *[!A-Za-z0-9_.:-]*|'') printf 'Invalid parent interface: %s\n' "$parent_if" >&2; exit 2 ;; esac
case "$shim_if" in *[!A-Za-z0-9_.:-]*|'') printf 'Invalid shim interface: %s\n' "$shim_if" >&2; exit 2 ;; esac
case "$host_cidr" in *[!A-Za-z0-9_./:-]*) printf 'Invalid host CIDR: %s\n' "$host_cidr" >&2; exit 2 ;; esac
if [ ${#parent_if} -gt 15 ]; then
    printf 'Parent interface name is too long for Linux interfaces: %s\n' "$parent_if" >&2
    exit 2
fi
if [ ${#shim_if} -gt 15 ]; then
    printf 'Shim interface name is too long for Linux interfaces: %s\n' "$shim_if" >&2
    exit 2
fi

output_dir=$(dirname -- "$output_file")
mkdir -p "$output_dir"

{
    printf '%s\n' '# Local macvlan lab profile generated by scripts/write-macvlan-profile.sh.'
    printf '%s\n' '# This file is project-owned configuration; review before using it for lifecycle scripts.'
    printf '\n'
    printf 'LXC_LAB_PREFIX=%s\n' "$prefix"
    printf 'LXC_LAB_STATE_DIR=%s\n' "$state_dir"
    printf 'LXC_LAB_CONTAINER=%s\n' "$name"
    printf 'LXC_LAB_PARENT_IF=%s\n' "$parent_if"
    printf 'LXC_LAB_SHIM_IF=%s\n' "$shim_if"
    printf 'LXC_LAB_HOST_SHIM_CIDR=%s\n' "$host_cidr"
} >"$output_file"

printf 'Wrote macvlan lab profile: %s\n' "$output_file"
printf 'No container was started and no networking was changed.\n'
